<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>coffee_item</name>
   <tag></tag>
   <elementGuidId>ba67b236-525a-4307-a14f-16e805916c86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item-box-top > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='items-list-init']/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://martintestforpackage.sandbox.arcadier.io/images/items/item-53271-637620140074604258-ksz0f6.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;items-list-init&quot;)/div[@class=&quot;item-box col-md-3 col-sm-4 col-xs-6 find-flag&quot;]/div[@class=&quot;item-box-inner&quot;]/div[@class=&quot;item-box-top&quot;]/a[1]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='items-list-init']/div/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://martintestforpackage.sandbox.arcadier.io/images/items/item-53271-637620140074604258-ksz0f6.jpg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
