<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search_button</name>
   <tag></tag>
   <elementGuidId>775ae9cd-84f6-4f96-ad0d-7e5cf7445910</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.h-search-bar > input.btn-find</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-find</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-407a77b4-a023-e911-80e1-000d3aa0a08d&quot;)/div[@class=&quot;banner-inner banner-flex&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;banner-row-flex&quot;]/div[@class=&quot;home-serach home-serach-remove-position&quot;]/form[1]/div[@class=&quot;search-controls&quot;]/div[@class=&quot;h-search-bar&quot;]/input[@class=&quot;btn-find&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-407a77b4-a023-e911-80e1-000d3aa0a08d']/div/div/div/div[2]/form/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
